import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Chapters are ordered by the number prefix of their folder (01-, 02-, …).
// Pages inside a chapter are ordered by `sidebar_position` in their front matter.
const sidebars: SidebarsConfig = {
  architecture: [
    'index',
    {type: 'autogenerated', dirName: 'arc42'},
    {
      type: 'category',
      label: 'Appendices',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'appendix'}],
    },
  ],
  readers: [{type: 'autogenerated', dirName: 'readers'}],
  handbook: [{type: 'autogenerated', dirName: 'handbook'}],
};

export default sidebars;
